version: "2.1"

volumes:
  html:
  mysql:

services:
  # https://hub.docker.com/_/nextcloud/
  app:
    build: app
    privileged: true
    volumes:
      - html:/var/www/html
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: "*.balena-devices.com"
      MYSQL_HOST: db
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: nextcloud
      BALENA_HOSTNAME: nextcloud
    depends_on:
      - db
      - redis
    labels:
      io.balena.features.supervisor-api: 1

  # https://hub.docker.com/_/nextcloud/
  cron:
    build: app
    privileged: true
    entrypoint: /cron.sh
    volumes:
      - html:/var/www/html
    depends_on:
      - app

  # https://hub.docker.com/_/nginx/
  web:
    build: web
    ports:
      - 80:80/tcp
    volumes:
      - html:/var/www/html:ro
    depends_on:
      - app

  # https://hub.docker.com/r/yobasystems/alpine-mariadb
  db:
    build: db
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: nextcloud
      MYSQL_ROOT_PASSWORD: balena

  # https://hub.docker.com/_/redis
  redis:
    image: redis:6.0.8-alpine
    command: redis-server --requirepass nextcloud
